### ISSUE TITLE
Fails for all captcha's except the provided 4

### ISSUE THREAD

**Issue by RobThree** [andreluizsecco/RecogCaptcha#1]
The following test images (the first random 17 **easy ones** I could find on Google Images) all fail...

[fail.zip](https://github.com/andreluizsecco/RecogCaptcha/files/387376/fail.zip)

**Comment by andreluizsecco** [comment]
Hello Rob,
The project is not generic. You need to create your filters for one or more specific types of captchas.
I recommend reading the article I wrote. The link is in the README

**Comment by RobThree** [comment]
> I recommend reading the article I wrote

The [link in the readme](http://andresecco.com.br/2015/09/reconhecimento-de-captcha-com-aforge-net-e-tesseract/) ([after translating](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fandresecco.com.br%2F2015%2F09%2Freconhecimento-de-captcha-com-aforge-net-e-tesseract%2F&edit-text=&act=url)) provides no information whatsoever; the [link in *that* page](http://netcoders.com.br/blog/reconhecimento-de-captcha-com-aforge-net-e-tesseract/) (again, [after translate](https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=en&ie=UTF8&prev=_t&rurl=translate.google.com&sl=auto&tl=en&u=http://netcoders.com.br/blog/reconhecimento-de-captcha-com-aforge-net-e-tesseract&usg=ALkJrhh-w4VA2GERxMbdImHvRwYdWndHoQ))  also says *nothing* about it being generic or not. And because the 'explanation' is nothing but a bunch of screenshots and "here, copy/paste this code" it also doesn't help me (nor does it *explain* ) **how** I would "... create ... filters for one or more specific types of captchas."

So what good is that article then?

**Comment by andreluizsecco** [comment]
> also says nothing about it being generic or not

I think you have not read or do not know how to interpret

> Neste caso foi implementado alguns filtros específicos para um tipo de CAPTCHA. Caso você tenha outro padrão é necessário implementar ele utilizando outros filtros e/ou outra sequência.

OBS: Use translation again

**Comment by RobThree** [comment]
I read, after translating, the following:

> **Many services** ... available on the internet 

> Currently there are **several types** of CAPTCHA...

> There are cases where it is necessary to automate some tasks. But when you are stopped by a check of these, what to do? Well, there are several techniques to perform automatic recognition of CAPTCHA. One is using the AForge.NET with Tesseract.

This at least implies something much broader. Granted, further down it states (once):

> In this case some specific filters was implemented for one type of CAPTCHA. If you have other standard it is necessary to implement it using other filters and / or other sequence.

But then it goed on and never explains **how** I would implement a filter, why the filter in the example is the way it is (why you chose it to be like that), what my options are, what alternatives I might want to try... nothing.

**Comment by andreluizsecco** [comment]
I agree, can be improved. We can always improve. I do not know if you noticed but the intention of the article is to show the technique of integration between AForge.NET and Tesseract (and not focus on creating specific filters with AForge.NET, both having the proper tool documentation for exactly that, help you create these filters).
Anyway I appreciate the comments and PR is always welcome.

**Comment by RobThree** [comment]
> I do not know if you noticed but the intention of the article is to show the technique of integration between AForge.NET and Tesseract

Not really, no. You 'advertised' it on reddit as:

> How to Solve Captchas automaticaly (Code here)

The project is named:

> RecogCaptcha

The README (after translate) reads:

> recognition technique (breaks) of captchas **using** the framework AForge.NET and Tesseract

Which implies "recognition technique **using** something", not "Using AForge.NET and Tesseract building something". Same goes for the [MSDN link](https://code.msdn.microsoft.com/Solving-Captcha-with-C-dadf37cd):

> **Solving Captchas** with C#, AForge.NET and Tesseract

And your [site's link](http://andresecco.com.br/2015/09/reconhecimento-de-captcha-com-aforge-net-e-tesseract/):

> **Captcha Recognition** with AForge.NET and Tesseract

And the [netcoders.br link](https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http%3A%2F%2Fnetcoders.com.br%2Fblog%2Freconhecimento-de-captcha-com-aforge-net-e-tesseract%2F):

> **Captcha Recognition** with AForge.NET and Tesseract

You can't blame me for missing that the article is "to show the technique of integration between AForge.NET and Tesseract"; it isn't mentioned once nor is it obvious from the titles.

**Comment by andreluizsecco** [comment]
Really? You're crying because of the titles?
Why not spend that time doing a code or product better?
Have a Pull Request, do anything but stand crying not.

**Comment by RobThree** [comment]
I'm not "crying", I'm trying to help YOU write better articles in the future, help YOU pick better titles in the future, help YOU help others better (instead of "here, follow these steps exactly and copy/paste this and it will work", I'm trying to get across to YOU that:

> Give a man a fish and feed him for a day. Teach a man how to fish and feed him for a lifetime.

I'm trying to *teach* YOU (by questioning your choices, titles, etc., explaining that I'm missing a lot, showing that having the info posted spread over 4 different sites/pages isn't helpful, etc. etc.). If you think that's me crying then that's fine with me. But I won't "PR"; I'm not gonna *give* you your fish. :wave:

**Comment by RobThree** [comment]
Nice dick-move removing all comments. Glad I saved them!

![image](https://cloud.githubusercontent.com/assets/607888/17197201/effcdba4-546a-11e6-99cd-40fc5d976c2f.png)

**Comment by andreluizsecco** [comment]
The code is not generic. It is necessary to implement specific filters with AForge.NET to meet specifically the types of captcha. The code illustrates the integration between AForge.NET and Tesseract using C#
