### ISSUE TITLE
aforge.dll could not be found

### ISSUE THREAD

**Issue by hosseinalipour** [andreluizsecco/RecogCaptcha#2]
hello, thank you for this great decoder, after building solution I get these errors, how do I solve this?

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\landlord\Downloads\Solving Captchas with C_23, AForge.NET and Tesseract (3)\C#\RecogCaptcha\bin\Debug\AForge.dll' could not be found	RecogCaptcha	C:\Users\landlord\Downloads\Solving Captchas with C_23%2c AForge.NET and Tesseract (3)\C#\RecogCaptcha\CSC	1	Active
Error	CS0006	Metadata file 'C:\Users\landlord\Downloads\Solving Captchas with C_23, AForge.NET and Tesseract (3)\C#\RecogCaptcha\bin\Debug\AForge.Imaging.dll' could not be found	RecogCaptcha	C:\Users\landlord\Downloads\Solving Captchas with C_23%2c AForge.NET and Tesseract (3)\C#\RecogCaptcha\CSC	1	Active
Error	CS0006	Metadata file 'C:\Users\landlord\Downloads\Solving Captchas with C_23, AForge.NET and Tesseract (3)\C#\RecogCaptcha\bin\Debug\Tesseract.dll' could not be found	RecogCaptcha	C:\Users\landlord\Downloads\Solving Captchas with C_23%2c AForge.NET and Tesseract (3)\C#\RecogCaptcha\CSC	1	Active
Error	CS0246	The type or namespace name 'AForge' could not be found (are you missing a using directive or an assembly reference?)	RecogCaptcha	C:\Users\landlord\Downloads\Solving Captchas with C_23%2c AForge.NET and Tesseract (3)\C#\RecogCaptcha\Form1.cs	1	Active
Error	CS0246	The type or namespace name 'Tesseract' could not be found (are you missing a using directive or an assembly reference?)	RecogCaptcha	C:\Users\landlord\Downloads\Solving Captchas with C_23%2c AForge.NET and Tesseract (3)\C#\RecogCaptcha\Form1.cs	6	Active
Error	CS0246	The type or namespace name 'Erosion' could not be found (are you missing a using directive or an assembly reference?)	RecogCaptcha	C:\Users\landlord\Downloads\Solving Captchas with C_23%2c AForge.NET and Tesseract (3)\C#\RecogCaptcha\Form1.cs	37	Active
Error	CS0246	The type or namespace name 'Erosion' could not be found (are you missing a using directive or an assembly reference?)	RecogCaptcha	C:\Users\landlord\Downloads\Solving Captchas with C_23%2c AForge.NET and Tesseract (3)\C#\RecogCaptcha\Form1.cs	37	Active
Error	CS0246	The type or namespace name 'Dilatation' could not be found (are you missing a using directive or an assembly reference?)	RecogCaptcha	C:\Users\landlord\Downloads\Solving Captchas with C_23%2c AForge.NET and Tesseract (3)\C#\RecogCaptcha\Form1.cs	38	Active
Error	CS0246	The type or namespace name 'Dilatation' could not be found (are you missing a using directive or an assembly reference?)	RecogCaptcha	C:\Users\landlord\Downloads\Solving Captchas with C_23%2c AForge.NET and Tesseract (3)\C#\RecogCaptcha\Form1.cs	38	Active

**Comment by andreluizsecco** [comment]
Hello @HosseinAlipour, this project is very old and is still used references by dll files. This error occurred because this files was not found. I've done a commit and now I'm using nuget packages. Download the project again and try to run it
